PackageName: "LDLFactorizations"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "40e66cde-538c-5869-a4ad-c39174c6795b"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
